os: osx
osx_image: xcode10.1
language: swift
xcode_project: calc.xcodeproj
xcode_scheme: CalcTest
install: true
script:
  - xcodebuild clean test -project calc.xcodeproj -scheme CalcTest CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
